$schema: https://raw.githubusercontent.com/remal-github-actions/sync-with-template/main/local-transformations.schema.json

repositories:
- remal/github-repository-token-issuer

transformations:
- name: .github/sync-with-template.yml
  format: yaml
  includes:
  - .github/sync-with-template.yml
  script: |
    content.includes = content.includes ?? []
    ;[
    ].forEach(path => {
      if (!content.includes.includes(path)) {
        content.includes.push(path)
      }
    })
    content.excludes = content.excludes ?? []
    ;[
      '.github/workflows/release-drafter.yml',
      '.github/release-drafter.yml',
    ].forEach(path => {
      if (!content.excludes.includes(path)) {
        content.excludes.push(path)
      }
    })
    return content
