name: 'GitHub Repository Token Issuer'
description: 'Issues short-lived GitHub installation tokens with specific repository permissions'

inputs:
  scopes:
    description: 'Repository permission scopes (one per line, format: scope_id: permission)'
    required: true
  service_tag:
    description: 'Cloud Run service tag for canary deployments (e.g., "canary"). When set, uses the tag-specific URL.'
    required: false
    default: ''

outputs:
  token:
    description: 'The GitHub installation access token'
    value: ${{ steps.get-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Check dependencies
      shell: bash
      run: |
        # Check dependencies
        missing=()
        command -v curl &>/dev/null || missing+=("curl")
        command -v jq &>/dev/null || missing+=("jq")
        if [[ ${#missing[@]} -gt 0 ]]; then
          echo "Error: Missing required dependencies: ${missing[*]}"
          exit 1
        fi

    - name: Get GitHub OIDC Token
      id: oidc
      shell: bash
      run: |
        # Get GitHub OIDC Token
        RESPONSE=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gh-repo-token-issuer")
        if ! OIDC_TOKEN=$(echo "$RESPONSE" | jq -r '.value // empty' 2>/dev/null) || [[ -z "$OIDC_TOKEN" ]]; then
          echo "Error: Failed to get GitHub OIDC token"
          echo "$RESPONSE"
          exit 1
        fi
        echo "::add-mask::$OIDC_TOKEN"
        echo "token=$OIDC_TOKEN" >> $GITHUB_OUTPUT

    - name: Convert scopes to query params
      id: scopes
      shell: bash
      run: |
        # Convert scopes to query params
        QUERY=""
        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          SCOPE_ID=$(echo "${line%%:*}" | xargs)
          PERMISSION=$(echo "${line##*:}" | xargs)
          [[ -n "$QUERY" ]] && QUERY="${QUERY}&"
          QUERY="${QUERY}${SCOPE_ID}=${PERMISSION}"
        done <<< "${{ inputs.scopes }}"
        echo "query=$QUERY" >> $GITHUB_OUTPUT

    - name: Request Installation Token
      id: get-token
      shell: bash
      run: |
        # Request Installation Token
        if [[ -n "${{ inputs.service_tag }}" ]]; then
          SERVICE_URL="https://${{ inputs.service_tag }}---gh-repo-token-issuer-db7udto7gq-uk.a.run.app"
        else
          SERVICE_URL="https://gh-repo-token-issuer-db7udto7gq-uk.a.run.app"
        fi
        RESPONSE=$(curl -sS -X POST \
          -H "Authorization: Bearer ${{ steps.oidc.outputs.token }}" \
          "${SERVICE_URL}/token?${{ steps.scopes.outputs.query }}")
        if ! TOKEN=$(echo "$RESPONSE" | jq -r '.token // empty' 2>/dev/null); then
          echo "Error: Invalid response from token service"
          echo "$RESPONSE"
          exit 1
        fi
        if [[ -z "$TOKEN" ]]; then
          ERROR=$(echo "$RESPONSE" | jq -r '.error // empty' 2>/dev/null)
          echo "Error: ${ERROR:-Unknown error}"
          echo "$RESPONSE"
          exit 1
        fi
        echo "::add-mask::$TOKEN"
        echo "token=$TOKEN" >> $GITHUB_OUTPUT
