name: 'GitHub Repository Token Issuer'
description: 'Issues short-lived GitHub installation tokens with specific repository permissions'

inputs:
  scopes:
    description: 'Repository permission scopes (one per line, format: scope_id:permission)'
    required: true

outputs:
  token:
    description: 'The GitHub installation access token'
    value: ${{ steps.get-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Get GitHub OIDC Token
      id: oidc
      shell: bash
      run: |
        OIDC_TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gh-repo-token-issuer" | jq -r '.value')
        echo "::add-mask::$OIDC_TOKEN"
        echo "token=$OIDC_TOKEN" >> $GITHUB_OUTPUT

    - name: Exchange for GCP Token
      id: gcp
      shell: bash
      run: |
        GCP_TOKEN=$(curl -sS -X POST \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data-urlencode "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
          --data-urlencode "subject_token_type=urn:ietf:params:oauth:token-type:jwt" \
          --data-urlencode "subject_token=${{ steps.oidc.outputs.token }}" \
          --data-urlencode "audience=//iam.googleapis.com/projects/74155037973/locations/global/workloadIdentityPools/users-github-actions/providers/users-github-oidc" \
          "https://sts.googleapis.com/v1/token" | jq -r '.access_token')
        echo "::add-mask::$GCP_TOKEN"
        echo "token=$GCP_TOKEN" >> $GITHUB_OUTPUT

    - name: Convert scopes to query params
      id: scopes
      shell: bash
      run: |
        QUERY=""
        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          SCOPE_ID="${line%%:*}"
          PERMISSION="${line##*:}"
          [[ -n "$QUERY" ]] && QUERY="${QUERY}&"
          QUERY="${QUERY}${SCOPE_ID}=${PERMISSION}"
        done <<< "${{ inputs.scopes }}"
        echo "query=$QUERY" >> $GITHUB_OUTPUT

    - name: Request Installation Token
      id: get-token
      shell: bash
      run: |
        RESPONSE=$(curl -sS -X POST \
          -H "Authorization: Bearer ${{ steps.gcp.outputs.token }}" \
          -H "X-GitHub-Token: ${{ steps.oidc.outputs.token }}" \
          "https://gh-repo-token-issuer-db7udto7gq-uk.a.run.app/token?${{ steps.scopes.outputs.query }}")
        TOKEN=$(echo "$RESPONSE" | jq -r '.token // empty')
        if [[ -z "$TOKEN" ]]; then
          echo "Error: $(echo "$RESPONSE" | jq -r '.error // "Unknown error"')"
          exit 1
        fi
        echo "::add-mask::$TOKEN"
        echo "token=$TOKEN" >> $GITHUB_OUTPUT
